<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-08-28T22:12:18 IST" name="Suite" finished-at="2024-08-28T22:12:31 IST" duration-ms="13109">
    <groups>
    </groups>
    <test started-at="2024-08-28T22:12:18 IST" name="Positive Tests" finished-at="2024-08-28T22:12:26 IST" duration-ms="8721">
      <class name="viridiantooth34.tests.StandAloneTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:viridiantooth34.tests.StandAloneTest@4b2c5e02]" started-at="2024-08-28T22:12:18 IST" name="setUp" finished-at="2024-08-28T22:12:20 IST" duration-ms="2142" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="addToCart()[pri:0, instance:viridiantooth34.tests.StandAloneTest@4b2c5e02]" started-at="2024-08-28T22:12:20 IST" name="addToCart" finished-at="2024-08-28T22:12:25 IST" duration-ms="5716" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Order was not placed! expected [THANKYOU FOR THE ORDER._] but found [THANKYOU FOR THE ORDER.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Order was not placed! expected [THANKYOU FOR THE ORDER._] but found [THANKYOU FOR THE ORDER.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at viridiantooth34.tests.StandAloneTest.addToCart(StandAloneTest.java:64)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addToCart -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:viridiantooth34.tests.StandAloneTest@4b2c5e02]" started-at="2024-08-28T22:12:26 IST" name="tearDown" finished-at="2024-08-28T22:12:26 IST" duration-ms="118" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- viridiantooth34.tests.StandAloneTest -->
    </test> <!-- Positive Tests -->
    <test started-at="2024-08-28T22:12:26 IST" name="Negative Tests" finished-at="2024-08-28T22:12:31 IST" duration-ms="4221">
      <class name="viridiantooth34.tests.ErrorValidationTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:viridiantooth34.tests.ErrorValidationTest@50313382]" started-at="2024-08-28T22:12:26 IST" name="setUp" finished-at="2024-08-28T22:12:28 IST" duration-ms="1200" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="NegativeTest()[pri:0, instance:viridiantooth34.tests.ErrorValidationTest@50313382]" started-at="2024-08-28T22:12:28 IST" name="NegativeTest" finished-at="2024-08-28T22:12:31 IST" duration-ms="2897" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NegativeTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:viridiantooth34.tests.ErrorValidationTest@50313382]" started-at="2024-08-28T22:12:31 IST" name="tearDown" finished-at="2024-08-28T22:12:31 IST" duration-ms="121" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- viridiantooth34.tests.ErrorValidationTest -->
    </test> <!-- Negative Tests -->
  </suite> <!-- Suite -->
</testng-results>
